<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_jk</name>
   <tag></tag>
   <elementGuidId>205abefa-38a2-4af0-8061-cc03466902cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jk_pelanggan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jk_pelanggan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Jenis Kelamin&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a25eb2f-05e9-4218-8efe-57c0e8e41f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>01a57f08-a6da-4702-a5a7-51896c99d170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jk_pelanggan</value>
      <webElementGuid>3937921a-7687-45b2-8ce6-acbdd5f59d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>218a352c-06c8-4497-9a43-77373435ee99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jk_pelanggan</value>
      <webElementGuid>9d955813-eb54-49ef-a051-b0d92251b255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7cb8b39b-191c-4471-bcf8-3b9c90ed8d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tambah&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/form[1]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form-group&quot;]/input[@id=&quot;jk_pelanggan&quot;]</value>
      <webElementGuid>44cd933a-7042-4872-9f70-4763d1ca167e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jk_pelanggan']</value>
      <webElementGuid>bd4b4f2a-5f81-49e3-9d21-618aed2db7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tambah']/div/div/div/form/div/div[4]/input</value>
      <webElementGuid>612566a7-b494-4043-b143-c2b1dc532d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>bcbbb8ef-8a26-47be-9ded-6f8d72c1e626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'gender' and @name = 'jk_pelanggan' and @id = 'jk_pelanggan']</value>
      <webElementGuid>b0af58f4-660f-4d4d-92e3-ea53a6c05d82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
