<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat_alamat_cs</name>
   <tag></tag>
   <elementGuidId>d3db48c5-793a-4062-b995-e1803404e02f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='alamat_cs'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-edits > div.form-group > #alamat_cs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modal-edits #alamat_cs</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80d84f86-c7ed-429c-a414-1d90427febf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7893c436-9ad7-4270-80c4-24ca9c841698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alamat_cs</value>
      <webElementGuid>a94261b2-72a0-4a16-b0f1-eef80b17faca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6734fed9-b2e3-46ce-9086-fec5deabfaab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alamat_cs</value>
      <webElementGuid>8018c730-41a5-4456-a653-ad3659d5ffea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>62444a82-dc24-4342-a831-9797f22a0b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-edits&quot;)/div[@class=&quot;form-group&quot;]/input[@id=&quot;alamat_cs&quot;]</value>
      <webElementGuid>149e3f01-cf35-4bc2-9bd9-a369edc7b420</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='alamat_cs'])[2]</value>
      <webElementGuid>fa13dbe4-4cc0-4248-b078-d8cbc0442190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-edits']/div[4]/input</value>
      <webElementGuid>83955d1a-57ee-44f5-a807-2ea1cb893b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/form/div/div[4]/input</value>
      <webElementGuid>b2061749-ecbc-4291-9743-eb57255dafbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'alamat_cs' and @id = 'alamat_cs']</value>
      <webElementGuid>160b83cd-1d0c-4466-9dd5-dbb56d051452</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
