<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Laki-LakiPerempuan</name>
   <tag></tag>
   <elementGuidId>52636930-2041-4d2b-a4c7-8e93a973468e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='jk_cs'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-edits > div.form-group > #jk_cs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>91ffcb01-5aa5-42be-ac32-6bcd1f16c7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b2301d51-3970-4912-9633-e7fe3e241731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jk_cs</value>
      <webElementGuid>f9143281-fdee-4027-91c3-77c56ac5e982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jk_cs</value>
      <webElementGuid>12b02551-f6a7-4502-a0f0-b3fe4be8b09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
											Laki-Laki
											Perempuan
											</value>
      <webElementGuid>a7f37a91-5b69-4e16-9068-e0f674dfd8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-edits&quot;)/div[@class=&quot;form-group&quot;]/select[@id=&quot;jk_cs&quot;]</value>
      <webElementGuid>f446b39c-9696-4543-be89-489a71c78ef1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='jk_cs'])[2]</value>
      <webElementGuid>dbe8cc5b-ead7-4f3e-8a97-12bdbc8a87a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-edits']/div[3]/select</value>
      <webElementGuid>12432541-f48b-408f-92f5-61bca14fe376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Kelamin'])[3]/following::select[1]</value>
      <webElementGuid>a9f1fb8d-06d4-4380-b42b-1891f92abe90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Karyawan'])[3]/following::select[1]</value>
      <webElementGuid>adf10971-6a64-4225-bf87-9baf91476f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[3]/preceding::select[1]</value>
      <webElementGuid>2e96f184-87d5-4ddf-b7b3-1898d0f15e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. KTP'])[3]/preceding::select[1]</value>
      <webElementGuid>3f023b97-090e-4cb1-aff9-b62dce708bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/form/div/div[3]/select</value>
      <webElementGuid>5145b1e8-d47c-4f53-a140-26f556370d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jk_cs' and @id = 'jk_cs' and (text() = '
											Laki-Laki
											Perempuan
											' or . = '
											Laki-Laki
											Perempuan
											')]</value>
      <webElementGuid>82cadb0a-d1a4-4473-9ea3-2f2c548896f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
