<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Menu Rental</name>
   <tag></tag>
   <elementGuidId>71ff02b1-ed42-4863-a89d-65f495c0af58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper']/div/div/ol/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ol.breadcrumb > li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#page-wrapper li >> internal:has-text=&quot;Menu Rental&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b4e476c5-5828-4965-8580-779f5eefb3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Menu Rental </value>
      <webElementGuid>2f22f32e-e373-4207-862e-0e1a8ad9618d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/ol[@class=&quot;breadcrumb&quot;]/li[1]</value>
      <webElementGuid>85d3d14c-2bd0-4d33-8fc4-fd35372d6a61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div/div/ol/li</value>
      <webElementGuid>1d3fd8bb-5c06-41ee-bd30-e74b31b42278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Pelanggan'])[2]/following::li[1]</value>
      <webElementGuid>eb4f731e-8c3f-4b94-91e7-d4c9d959e507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Pelanggan'])[3]/preceding::li[1]</value>
      <webElementGuid>00570ca6-5674-4eb4-b438-d8acac9c77e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li</value>
      <webElementGuid>1b533204-1d7f-4486-a0e3-b9b75f5e3a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = ' Menu Rental ' or . = ' Menu Rental ')]</value>
      <webElementGuid>e7fd4ce1-73b6-4b01-8af5-0fcf17a77fdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
