<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HARUMAN RENT CAR</name>
   <tag></tag>
   <elementGuidId>7344a943-cf0d-4bcb-95e2-525eaba3ef66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.navbar-brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/nav/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;HARUMAN RENT CAR&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>925a337c-d600-497e-8d91-c5af901d7adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-brand</value>
      <webElementGuid>dfce483c-974d-417e-8b9a-6f12167f88f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?page=dashboard</value>
      <webElementGuid>f56b7d0a-5954-46eb-9255-0daca6f87a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HARUMAN RENT CAR</value>
      <webElementGuid>1cc86811-9e85-4590-b6e6-bc93889c8b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/nav[@class=&quot;navbar navbar-inverse navbar-fixed-top&quot;]/div[@class=&quot;navbar-header&quot;]/a[@class=&quot;navbar-brand&quot;]</value>
      <webElementGuid>825b1e3e-58e0-414a-ab64-cbb79e32dea6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/nav/div/a</value>
      <webElementGuid>7bc1fab1-8e22-43ea-80b7-0bbcd777745a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'HARUMAN RENT CAR')]</value>
      <webElementGuid>c1781faf-24cd-48b5-aac1-8341bb63236a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/following::a[1]</value>
      <webElementGuid>9aa65a03-e4c5-4a19-982d-5bb45d4d31ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Halaman Utama'])[1]/preceding::a[1]</value>
      <webElementGuid>fc66fd95-3c17-4ba7-8863-edc2e1bd9863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Mobil'])[1]/preceding::a[3]</value>
      <webElementGuid>d22ed8d1-bf46-49dd-adeb-f7a385855aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '?page=dashboard')]</value>
      <webElementGuid>7c09b58f-e964-44e5-b8c0-d9b7b74f0778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>6f3794e2-fc20-4b35-b304-3dca70dbfbab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?page=dashboard' and (text() = 'HARUMAN RENT CAR' or . = 'HARUMAN RENT CAR')]</value>
      <webElementGuid>dc6663b3-96d4-4443-a965-03f4eb1c0031</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
