<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Laki-LakiPerempuan</name>
   <tag></tag>
   <elementGuidId>e9941b7a-7b11-4d76-998c-b9e6f075f77c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jk_cs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jk_cs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Jenis Kelamin&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ce6ec67c-c610-4b69-b5ff-7eb1cf407c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>49ca6e54-bbb7-40b4-9860-2f41f3312238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jk_cs</value>
      <webElementGuid>864af259-e8ae-4692-a334-d9b9a303b763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jk_cs</value>
      <webElementGuid>c3a8bd63-7a36-48a6-b252-d9208ee4fb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
											Laki-Laki
											Perempuan
											</value>
      <webElementGuid>e2eb885b-175d-4db8-8bff-0a24cf389c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tambah&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/form[1]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form-group&quot;]/select[@id=&quot;jk_cs&quot;]</value>
      <webElementGuid>f6218c4e-6e68-4abd-aed0-633e0283a45f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jk_cs']</value>
      <webElementGuid>0044fc17-c685-44a2-ba60-57f0ed58f646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tambah']/div/div/form/div/div[3]/select</value>
      <webElementGuid>7b8c14ab-18c5-4e8c-b9e7-c82fbafc0e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Kelamin'])[2]/following::select[1]</value>
      <webElementGuid>ec4051cf-413c-426d-b6ca-0e59607d9a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Karyawan'])[2]/following::select[1]</value>
      <webElementGuid>7857ade6-0013-422d-a1a9-db9654720421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[2]/preceding::select[1]</value>
      <webElementGuid>e58e7c31-2d0b-4528-bd8d-59e90935e072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. KTP'])[2]/preceding::select[1]</value>
      <webElementGuid>54cf76d7-0ca4-424c-8332-c11cf36905f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ed1c4015-2831-43d7-aa5f-1b7c7781cb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'jk_cs' and @id = 'jk_cs' and (text() = '
											Laki-Laki
											Perempuan
											' or . = '
											Laki-Laki
											Perempuan
											')]</value>
      <webElementGuid>5d0588a1-db4e-4817-b94f-295cf9ee6250</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
