<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Stok Mobil_stok_mobil</name>
   <tag></tag>
   <elementGuidId>3b11a4a9-d4ce-416d-8e98-afebf47f444f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-edits > div.form-group > #stok_mobil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='stok_mobil'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modal-edits #stok_mobil</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da943c00-5a8a-4941-8907-8b8dfa2ae256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>3a773c04-50c8-474b-80c8-c9d7071e8cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stok mobil</value>
      <webElementGuid>51d579e4-90e6-4034-bc2a-3571474cbf7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e372b162-1548-4870-8f51-7233320661ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stok_mobil</value>
      <webElementGuid>d8c9f727-9106-4c52-a1e4-01cc07dd0140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-edits&quot;)/div[@class=&quot;form-group&quot;]/input[@id=&quot;stok_mobil&quot;]</value>
      <webElementGuid>bdd2449a-1a87-452e-938b-926992014f4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='stok_mobil'])[2]</value>
      <webElementGuid>56fbb0c2-11ba-49f0-a3d2-234244bcc8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-edits']/div[6]/input</value>
      <webElementGuid>1a07b270-4761-4c27-8c37-873b4d55ab26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/form/div/div[6]/input</value>
      <webElementGuid>9106979d-c7b1-471a-9c22-f85d7a664ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'stok mobil' and @id = 'stok_mobil']</value>
      <webElementGuid>cf720ba7-b2c1-4aa1-85fa-4f6d74fd5421</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
