<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Merk Mobil_merk_mobil</name>
   <tag></tag>
   <elementGuidId>28d97817-9b5a-4d77-93a5-c34df8578c8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-edits > div.form-group > #merk_mobil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='merk_mobil'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modal-edits #merk_mobil</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>903f4d59-fa74-4f86-8ecb-6cdba733c3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0244c836-0959-43e1-afa8-f8cf829afd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>merk_mobil</value>
      <webElementGuid>1771f08b-73b8-4ed3-9e14-490a78e10de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>66371617-0e68-466f-b35d-c723d590cbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>merk_mobil</value>
      <webElementGuid>aaf1eaa4-54d7-4162-9800-32285a90f1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>91be42f3-d978-4bb4-8270-cf5633776a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-edits&quot;)/div[@class=&quot;form-group&quot;]/input[@id=&quot;merk_mobil&quot;]</value>
      <webElementGuid>940233c2-ecf0-47cf-a2bf-c39421f83da8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='merk_mobil'])[2]</value>
      <webElementGuid>85289fbc-6612-4124-853c-4b869138c341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-edits']/div[2]/input</value>
      <webElementGuid>bd1a1bb4-3810-47a2-823f-fd96f5547c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/form/div/div[2]/input</value>
      <webElementGuid>3759ba7c-08d5-48cc-963a-6a50c3d8d832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'merk_mobil' and @id = 'merk_mobil']</value>
      <webElementGuid>59363929-39f9-4282-ad95-b6dff2217155</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
