<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tahun di Buat_thn_buat</name>
   <tag></tag>
   <elementGuidId>437a2058-eb8c-40ed-b665-94d7b19ba56e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-edits > div.form-group > #thn_buat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='thn_buat'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modal-edits #thn_buat</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>003a2520-dd86-4247-b512-ebef28b784dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>28e8c9ba-155e-49cc-963e-38efa05ef0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>thn_buat</value>
      <webElementGuid>365aa2d0-e265-43a9-a942-ca3506262fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2700b1ec-aabd-4b96-96b7-d5f5d3db3208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>thn_buat</value>
      <webElementGuid>bdb8bd90-60e9-4d5c-b453-f3752352137d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2d2642cd-4574-4a7f-a3c5-f016cddad473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-edits&quot;)/div[@class=&quot;form-group&quot;]/input[@id=&quot;thn_buat&quot;]</value>
      <webElementGuid>60a0318c-53b2-4edc-911a-0ae0458b8ce9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='thn_buat'])[2]</value>
      <webElementGuid>21dc4f66-f663-44b3-93fa-97c1d406e073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-edits']/div[4]/input</value>
      <webElementGuid>e31720f2-4976-4035-820b-1adec30cbf3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/form/div/div[4]/input</value>
      <webElementGuid>34c79363-a016-40bc-b696-197fdf5e15b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'thn_buat' and @id = 'thn_buat']</value>
      <webElementGuid>03b2682e-c42c-45ab-886b-1d9447d21c63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
