<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type Mobil_tipe_mobil</name>
   <tag></tag>
   <elementGuidId>17ca5b94-d949-4f38-92cf-4b26fcf6a1cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-edits > div.form-group > #tipe_mobil</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='tipe_mobil'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modal-edits #tipe_mobil</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5772b19a-b323-48a9-8466-a244c115373d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>037aa962-0c1e-4ec1-af13-fea218621d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tipe_mobil</value>
      <webElementGuid>eb8e5cf2-05e5-401f-bd1b-841360918ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>621ea99a-a037-4278-a549-043562b234b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipe_mobil</value>
      <webElementGuid>8f4a0cb3-4098-4ab5-b3cb-45809106771a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>911dd2b8-25f6-4126-b5d3-4f9d72cf1bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-edits&quot;)/div[@class=&quot;form-group&quot;]/input[@id=&quot;tipe_mobil&quot;]</value>
      <webElementGuid>a67ea6d6-4133-417b-a8c7-b4547ac36345</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='tipe_mobil'])[2]</value>
      <webElementGuid>c03163fe-a42b-462f-b6a7-b44db9e66eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-edits']/div[3]/input</value>
      <webElementGuid>7e653561-c2d6-4afa-aa38-5773c54ecf45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/form/div/div[3]/input</value>
      <webElementGuid>a5ca8185-aba6-42b9-a3f3-871da3b898b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tipe_mobil' and @id = 'tipe_mobil']</value>
      <webElementGuid>000aa448-b5dd-4a47-80f9-6600fe83ea1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
