<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Plat Nomor Mobil Yang Akan Diubah_plat_nomor</name>
   <tag></tag>
   <elementGuidId>2d1826b0-a7a2-410b-b078-30350dcfcd70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-edits > div.form-group > #plat_nomor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='plat_nomor'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modal-edits #plat_nomor</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c54aa27b-7b05-4bdb-ae19-e2d1ee895288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf69022a-b12b-4077-83c8-34c1b916dbe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>plat_nomor</value>
      <webElementGuid>b0367e9b-1ef0-4704-8a54-264b77a29699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7722297b-8bde-4cc5-bc9c-690ac13edf34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plat_nomor</value>
      <webElementGuid>9d0afa95-2feb-4822-9aba-7a42dd0fc756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1dcafca4-b018-409f-800c-200a43cd6ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-edits&quot;)/div[@class=&quot;form-group&quot;]/input[@id=&quot;plat_nomor&quot;]</value>
      <webElementGuid>6ffd1d2f-c233-4c3a-a57a-214b7fe8e08b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='plat_nomor'])[2]</value>
      <webElementGuid>423a99c2-670c-4501-9093-8f9f516df279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-edits']/div/input</value>
      <webElementGuid>03a5f05c-533f-4bfc-8901-9e19f7a2b6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/form/div/div/input</value>
      <webElementGuid>cadf2867-24df-42df-ae8d-597b8d75e99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'plat_nomor' and @id = 'plat_nomor']</value>
      <webElementGuid>edf997a9-a122-431a-a29a-eeb8eaf06925</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
