<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Edit Data Karyawan</name>
   <tag></tag>
   <elementGuidId>85991e6d-21dc-4ccc-af86-ea701e381e72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edit > div.modal-dialog > div.modal-content > div.modal-header > h4.modal-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='edit']/div/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Edit Data Karyawan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>0bb48037-4e95-4a2b-84fb-398bdd700f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>7119d496-8c29-47b4-884c-284dba5e04f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit Data Karyawan</value>
      <webElementGuid>694f7644-2ea5-4925-b38a-b94944627583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/h4[@class=&quot;modal-title&quot;]</value>
      <webElementGuid>e957fdcc-2d51-44b0-aa7a-010360a52f98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edit']/div/div/div/h4</value>
      <webElementGuid>74e8f4f7-723f-4966-bf1a-3320c2b7f056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::h4[1]</value>
      <webElementGuid>7fe38846-67d8-41e2-9453-4b7b382948ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cetak Data'])[1]/following::h4[1]</value>
      <webElementGuid>ea916f8d-59cf-4996-8b8e-093c6655c075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Karyawan Yang Akan diubah'])[1]/preceding::h4[1]</value>
      <webElementGuid>95957d57-c06d-45e9-bfee-cee7617e60cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Karyawan'])[3]/preceding::h4[1]</value>
      <webElementGuid>fcbf4590-5d8b-4386-8010-c65d713d3857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit Data Karyawan']/parent::*</value>
      <webElementGuid>9af99277-73a8-4deb-a155-34a33e1b1444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/h4</value>
      <webElementGuid>07629212-b5d7-4e15-a6ff-3429157fc669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Edit Data Karyawan' or . = 'Edit Data Karyawan')]</value>
      <webElementGuid>4ac53847-3778-4723-ab00-c3b90da76527</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
