<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tabel_karyawan_semua</name>
   <tag></tag>
   <elementGuidId>67442154-9f38-48ba-b8ee-7304e916f018</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;table-respondsive&quot;]//table/tbody</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'ID Karyawan' or . = 'ID Karyawan')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;ID Karyawan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>c790f753-326d-4d70-89f9-414a2253ed72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ID Karyawan</value>
      <webElementGuid>6282b079-9c88-46d0-ac35-f29136b0114d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/div[@class=&quot;table-respondsive&quot;]/table[@class=&quot;table table-bordered table-hover table-striped&quot;]/tbody[1]/tr&#xd;
</value>
      <webElementGuid>56668486-c77e-4d44-8ddb-fbb21a4ef70d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper']/div[3]/div/div/table/tbody/tr/th</value>
      <webElementGuid>e2d632dc-f111-4fec-97dd-9f7dbf0e69b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari!'])[1]/following::th[1]</value>
      <webElementGuid>f377bfd1-0527-4919-8066-42ab1da7145d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan Daftar Karyawan'])[1]/following::th[1]</value>
      <webElementGuid>69686147-ea0e-47ef-bf7f-1248022eec83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Karyawan'])[1]/preceding::th[1]</value>
      <webElementGuid>87f82d28-c55d-4192-96fe-effa49a67f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Kelamin'])[1]/preceding::th[2]</value>
      <webElementGuid>fa07ee53-2371-49ec-85e6-b92096232d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ID Karyawan']/parent::*</value>
      <webElementGuid>c4a3b7fc-96b2-44c7-b671-c36697658860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th</value>
      <webElementGuid>7e76dafc-46ab-47ae-9bab-11f69a37dcf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'ID Karyawan' or . = 'ID Karyawan')]</value>
      <webElementGuid>8b2c3f7e-7cdc-4ca4-b0ff-a6b83e1757cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
